# Generated by Django 3.2.4 on 2021-07-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenamiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='costo_depar',
            field=models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Costo'),
        ),
    ]
